# Generated by Django 2.0 on 2018-01-24 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deklaracja',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('celizakres', models.CharField(blank=True, db_column='CelIzakres', max_length=2000, null=True)),
                ('opis', models.CharField(blank=True, db_column='Opis', max_length=2000, null=True)),
            ],
            options={
                'db_table': 'deklaracja',
            },
        ),
        migrations.CreateModel(
            name='FormaStudiow',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nazwaformy', models.CharField(db_column='nazwaFormy', max_length=255, unique=True)),
            ],
            options={
                'db_table': 'formastudiow',
            },
        ),
        migrations.CreateModel(
            name='JezykRealizacji',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nazwajezyka', models.CharField(db_column='nazwaJezyka', max_length=255, unique=True)),
            ],
            options={
                'db_table': 'jezykrealizacji',
            },
        ),
        migrations.CreateModel(
            name='NauczycielAkademicki',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('login', models.CharField(db_column='Login', max_length=30, unique=True)),
                ('haslo', models.CharField(db_column='Haslo', max_length=255)),
                ('imie', models.CharField(db_column='Imie', max_length=255)),
                ('nazwisko', models.CharField(db_column='Nazwisko', max_length=255)),
                ('sumagodzin', models.IntegerField(db_column='SumaGodzin')),
            ],
            options={
                'db_table': 'nauczycielakademicki',
            },
        ),
        migrations.CreateModel(
            name='PowiadomienieOWyborzeTematu',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nauczycielakademickiid', models.ForeignKey(db_column='NauczycielAkademickiID', on_delete=django.db.models.deletion.DO_NOTHING, to='dyplomowanie.NauczycielAkademicki')),
            ],
            options={
                'db_table': 'powiadomienieowyborzetematu',
            },
        ),
        migrations.CreateModel(
            name='StopienStudiow',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('stopien', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'stopienstudiow',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('login', models.CharField(db_column='Login', max_length=30, unique=True)),
                ('haslo', models.CharField(db_column='Haslo', max_length=255)),
                ('imie', models.CharField(db_column='Imie', max_length=255)),
                ('nazwisko', models.CharField(db_column='Nazwisko', max_length=255)),
                ('nrindeksu', models.CharField(db_column='NrIndeksu', max_length=9, unique=True)),
                ('kierunekstudiow', models.CharField(db_column='KierunekStudiow', max_length=255)),
                ('specjalnosc', models.CharField(blank=True, db_column='Specjalnosc', max_length=255, null=True)),
                ('rokstudiow', models.IntegerField(db_column='RokStudiow')),
                ('formastudiow', models.ForeignKey(db_column='FormaStudiow', on_delete=django.db.models.deletion.DO_NOTHING, to='dyplomowanie.FormaStudiow')),
                ('stopienstudiow', models.ForeignKey(db_column='StopienStudiow', on_delete=django.db.models.deletion.DO_NOTHING, to='dyplomowanie.StopienStudiow')),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Temat',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('trescpl', models.CharField(db_column='TrescPL', max_length=255)),
                ('tresceng', models.CharField(db_column='TrescENG', max_length=255)),
                ('maxiloscrealizujacych', models.IntegerField(db_column='MaxIloscRealizujacych')),
                ('czyzatwierdzony', models.IntegerField(db_column='CzyZatwierdzony')),
                ('czywolny', models.IntegerField(db_column='CzyWolny')),
                ('czyzaliczona', models.IntegerField(blank=True, db_column='CzyZaliczona', null=True)),
                ('czyplagiat', models.IntegerField(blank=True, db_column='CzyPlagiat', null=True)),
                ('jezykrealizacji', models.ForeignKey(blank=True, db_column='JezykRealizacji', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dyplomowanie.JezykRealizacji')),
                ('nauczycielakademickiid', models.ForeignKey(db_column='NauczycielAkademickiID', on_delete=django.db.models.deletion.DO_NOTHING, to='dyplomowanie.NauczycielAkademicki')),
            ],
            options={
                'db_table': 'temat',
            },
        ),
        migrations.CreateModel(
            name='TypPracy',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nazwatypu', models.CharField(db_column='nazwaTypu', max_length=255, unique=True)),
            ],
            options={
                'db_table': 'typpracy',
            },
        ),
        migrations.AddField(
            model_name='temat',
            name='typ',
            field=models.ForeignKey(db_column='Typ', on_delete=django.db.models.deletion.DO_NOTHING, to='dyplomowanie.TypPracy'),
        ),
        migrations.AddField(
            model_name='student',
            name='tematid',
            field=models.ForeignKey(blank=True, db_column='TematID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dyplomowanie.Temat'),
        ),
        migrations.AddField(
            model_name='powiadomienieowyborzetematu',
            name='studentid',
            field=models.ForeignKey(db_column='StudentID', on_delete=django.db.models.deletion.DO_NOTHING, to='dyplomowanie.Student'),
        ),
        migrations.AddField(
            model_name='powiadomienieowyborzetematu',
            name='tematid',
            field=models.ForeignKey(db_column='TematID', on_delete=django.db.models.deletion.DO_NOTHING, to='dyplomowanie.Temat'),
        ),
        migrations.AddField(
            model_name='deklaracja',
            name='studentid',
            field=models.ForeignKey(db_column='StudentID', on_delete=django.db.models.deletion.DO_NOTHING, to='dyplomowanie.Student'),
        ),
        migrations.AddField(
            model_name='deklaracja',
            name='tematid',
            field=models.ForeignKey(db_column='TematID', on_delete=django.db.models.deletion.DO_NOTHING, to='dyplomowanie.Temat'),
        ),
    ]
