# Generated by Django 2.0 on 2018-01-23 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dyplomowanie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deklaracja',
            options={},
        ),
        migrations.AlterModelOptions(
            name='formastudiow',
            options={},
        ),
        migrations.AlterModelOptions(
            name='jezykrealizacji',
            options={},
        ),
        migrations.AlterModelOptions(
            name='nauczycielakademicki',
            options={},
        ),
        migrations.AlterModelOptions(
            name='powiadomienieowyborzetematu',
            options={},
        ),
        migrations.AlterModelOptions(
            name='stopienstudiow',
            options={},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.AlterModelOptions(
            name='temat',
            options={},
        ),
        migrations.AlterModelOptions(
            name='typpracy',
            options={},
        ),
    ]
